version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
        - internal
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports: 
      - "5432:5432"
    volumes:
        - ./mnt/postgresql:/var/lib/postgresql
    restart: always

  pgadmim:
    image: dpage/pgadmin4
    container_name: pgadmim4
    networks:
        - internal
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8765:80"
    volumes:
      - ./mnt/pgadmin:/var/lib/pgadmin
    restart: always

networks:
  internal:
